packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
minimumReleaseAgeExclude:
  - hdrify
  - tanstack-router-ga4
  - '@clidoc/core'
  - '@clidoc/yargs'
  - humanize-units
  - vitest-command-line
  - yargs-file-commands
